// src/api/auth.js
import apiClient from './client'

/**
 * Bootstraps the CSRF protection for Sanctum across different domains.
 * This MUST be called before any authentication attempts and immediately after.
 */
export async function fetchCsrfCookie() {
  // 1. Establish/refresh the session cookie with the backend
  await apiClient.get('/sanctum/csrf-cookie', {
    baseURL: import.meta.env.VITE_API_URL.replace(/\/api\/?$/, '') 
  });

  // 2. Fetch the current readable token from our secure endpoint
  const response = await apiClient.get('/auth/csrf');
  
  // 3. Manually inject the token into Axios so it is sent on all subsequent POSTs
  apiClient.defaults.headers.common['X-XSRF-TOKEN'] = response.data.csrf_token;
}

export async function register(data) {
  await fetchCsrfCookie(); // Get pre-flight token
  const response = await apiClient.post('/auth/register', data);
  await fetchCsrfCookie(); // Re-sync the new token generated by session regeneration
  return response;
}

export async function login(data) {
  await fetchCsrfCookie(); // Get pre-flight token
  const response = await apiClient.post('/auth/login', data);
  await fetchCsrfCookie(); // Re-sync the new token generated by session regeneration
  return response;
}

export async function logout() {
  const response = await apiClient.post('/auth/logout');
  // Clear the defunct token from headers
  delete apiClient.defaults.headers.common['X-XSRF-TOKEN'];
  return response;
}

export function getMe() {
  return apiClient.get('/auth/me');
}